# Generated by Django 5.2.4 on 2025-08-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_election_remove_candidate_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Election',
        ),
    ]
