# Generated by Django 5.2.4 on 2025-08-20 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.voter'),
        ),
    ]
